import type { Metadata } from "next";
import { Inter, Oxygen } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const oxygen = Oxygen({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >{children}</body>
        {/*<body className={oxygen.className}>{children}</body> */}
    </html>
  );
}
